name: project_sample_base
description: &#x27;A new Flutter project. Created by Slidy&#x27;
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  projectbasesnow:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^4.1.1
  mobx_codegen: ^1.0.3
  build_runner: ^1.8.1
  effective_dart: ^1.2.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true